begin;
select plan(31);
select has_table('public', 'personal_notes', 'personal_notes exists');
select row_security_active('public.personal_notes'), 'RLS is active';
select policies_are('public', 'personal_notes', array['Authenticated users can select shared notes','owners_delete_personal_notes','owners_insert_personal_notes','owners_select_personal_notes','owners_update_personal_notes']);
select table_privs_are('public', 'personal_notes', 'anon', array[]::text[], 'anon has no table grants');
select table_privs_are('public', 'personal_notes', 'authenticated', array['DELETE','INSERT','SELECT','UPDATE'], 'authenticated grants are explicit');
select policy_roles_are('public', 'personal_notes', 'owners_select_personal_notes', array['authenticated']);
select policy_cmd_is('public', 'personal_notes', 'owners_update_personal_notes', 'UPDATE');
select isnt((select with_check from pg_policies where schemaname='public' and tablename='personal_notes' and policyname='owners_update_personal_notes'), null, 'update has WITH CHECK');
select policy_cmd_is('public', 'personal_notes', 'Authenticated users can select shared notes', 'SELECT');
select like((select qual from pg_policies where schemaname='public' and tablename='personal_notes' and policyname='Authenticated users can select shared notes'), '%shared%', 'shared note select policy is visibility-gated');
select has_table('public', 'user_selections', 'user_selections exists');
select row_security_active('public.user_selections'), 'user_selections RLS is active';
select policies_are('public', 'user_selections', array['active_companions_select_group_selections','owners_delete_user_selections','owners_insert_user_selections','owners_update_user_selections']);
select like((select qual from pg_policies where schemaname='public' and tablename='user_selections' and policyname='active_companions_select_group_selections'), '%object_kind = ''event''%', 'companion selection sharing is event-only');
select like((select qual from pg_policies where schemaname='public' and tablename='user_selections' and policyname='active_companions_select_group_selections'), '%selection_key = ''state''%', 'companion selection sharing is planning-state-only');
select table_privs_are('public', 'user_selections', 'anon', array[]::text[], 'anon has no user_selections grants');
select table_privs_are('public', 'user_selections', 'authenticated', array['DELETE','INSERT','SELECT','UPDATE'], 'authenticated user_selections grants are explicit');
select has_table('public', 'companion_members', 'companion_members exists');
select row_security_active('public.companion_members'), 'companion_members RLS is active';
select policies_are('public', 'companion_members', array['authenticated_select_active_companion_members']);
select table_privs_are('public', 'companion_members', 'anon', array[]::text[], 'anon has no companion_members grants');
select table_privs_are('public', 'companion_members', 'authenticated', array['SELECT'], 'authenticated can read active companion roster');
select results_eq($$ select count(*)::integer from public.companion_members where active $$, array[4], 'baseline companion roster has four active members');
select results_eq($$ select count(*)::integer from public.companion_members where black_lotus_entitled $$, array[2], 'only Kavi and Chris are baseline Black Lotus entitled');
select has_table('public', 'note_mentions', 'note_mentions exists');
select row_security_active('public.note_mentions'), 'note_mentions RLS is active';
select policies_are('public', 'note_mentions', array['note_mentions_delete_owner','note_mentions_insert_owner','note_mentions_select_owner_or_target','note_mentions_update_owner_or_target']);
select table_privs_are('public', 'note_mentions', 'anon', array[]::text[], 'anon has no note_mentions grants');
select table_privs_are('public', 'note_mentions', 'authenticated', array['DELETE','INSERT','SELECT','UPDATE'], 'authenticated grants are explicit on note_mentions');
select col_is_fk('public', 'note_mentions', 'note_id', 'note_id has a foreign key');
select col_is_fk('public', 'note_mentions', 'mentioned_person_key', 'mentioned_person_key has a foreign key');
select col_is_unique('public', 'note_mentions', array['note_id','mentioned_person_key'], 'one mention row per note/person');
select * from finish();
rollback;
