begin;
select plan(22);
select has_table('public', 'personal_notes', 'personal_notes exists');
select row_security_active('public.personal_notes'), 'RLS is active';
select policies_are('public', 'personal_notes', array['Authenticated users can select shared notes','owners_delete_personal_notes','owners_insert_personal_notes','owners_select_personal_notes','owners_update_personal_notes']);
select table_privs_are('public', 'personal_notes', 'anon', array[]::text[], 'anon has no table grants');
select table_privs_are('public', 'personal_notes', 'authenticated', array['DELETE','INSERT','SELECT','UPDATE'], 'authenticated grants are explicit');
select policy_roles_are('public', 'personal_notes', 'owners_select_personal_notes', array['authenticated']);
select policy_cmd_is('public', 'personal_notes', 'owners_update_personal_notes', 'UPDATE');
select isnt((select with_check from pg_policies where schemaname='public' and tablename='personal_notes' and policyname='owners_update_personal_notes'), null, 'update has WITH CHECK');
select policy_cmd_is('public', 'personal_notes', 'Authenticated users can select shared notes', 'SELECT');
select like((select qual from pg_policies where schemaname='public' and tablename='personal_notes' and policyname='Authenticated users can select shared notes'), '%shared%', 'shared note select policy is visibility-gated');
select has_table('public', 'user_selections', 'user_selections exists');
select row_security_active('public.user_selections'), 'user_selections RLS is active';
select policies_are('public', 'user_selections', array['owners_delete_user_selections','owners_insert_user_selections','owners_select_user_selections','owners_update_user_selections']);
select table_privs_are('public', 'user_selections', 'anon', array[]::text[], 'anon has no user_selections grants');
select table_privs_are('public', 'user_selections', 'authenticated', array['DELETE','INSERT','SELECT','UPDATE'], 'authenticated user_selections grants are explicit');
select has_table('public', 'companion_members', 'companion_members exists');
select row_security_active('public.companion_members'), 'companion_members RLS is active';
select policies_are('public', 'companion_members', array['authenticated_select_active_companion_members']);
select table_privs_are('public', 'companion_members', 'anon', array[]::text[], 'anon has no companion_members grants');
select table_privs_are('public', 'companion_members', 'authenticated', array['SELECT'], 'authenticated can read active companion roster');
select results_eq($$ select count(*)::integer from public.companion_members where active $$, array[4], 'baseline companion roster has four active members');
select results_eq($$ select count(*)::integer from public.companion_members where black_lotus_entitled $$, array[2], 'only Kavi and Chris are baseline Black Lotus entitled');
select * from finish();
rollback;
