import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const workingDir = path.join(repoRoot, 'local-assets', 'artist-card-working')
const cardCsvPath = fs.existsSync(path.join(workingDir, 'ManaBox_Collection_Art_Taxonomy_v2_with_Prices.csv'))
  ? path.join(workingDir, 'ManaBox_Collection_Art_Taxonomy_v2_with_Prices.csv')
  : path.join(workingDir, 'cards with price.csv')
const profileCsvPath = path.join(workingDir, 'artist_profiles.normalized.csv')
const outputPath = path.join(workingDir, 'artist_card_catalog_seed.sql')

const confirmedAtlantaArtists = new Set(['Cynthia Sheppard', 'Mark Poole', 'Serena Malyon'])
const unconfirmedAtlantaArtists = new Set(['Rebecca Guay'])
const atlantaAppearanceArtists = new Set([...confirmedAtlantaArtists, ...unconfirmedAtlantaArtists])

function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i]
    const next = text[i + 1]
    if (inQuotes) {
      if (char === '"' && next === '"') {
        field += '"'
        i += 1
      } else if (char === '"') {
        inQuotes = false
      } else {
        field += char
      }
    } else if (char === '"') {
      inQuotes = true
    } else if (char === ',') {
      row.push(field)
      field = ''
    } else if (char === '\n') {
      row.push(field)
      rows.push(row)
      row = []
      field = ''
    } else if (char !== '\r') {
      field += char
    }
  }

  if (field || row.length) {
    row.push(field)
    rows.push(row)
  }

  const [headers, ...body] = rows
  return body
    .filter(values => values.some(value => String(value ?? '').trim()))
    .map(values => Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])))
}

function readText(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing required import file: ${filePath}`)
  }
  return fs.readFileSync(filePath, 'utf8')
}

function sha256(text) {
  return crypto.createHash('sha256').update(text).digest('hex')
}

function sql(value) {
  if (value === null || value === undefined || value === '') return 'null'
  return `'${String(value).replaceAll("'", "''")}'`
}

function sqlNumber(value) {
  const parsed = Number.parseFloat(String(value ?? '').replace(/[^0-9.-]/g, ''))
  return Number.isFinite(parsed) ? String(parsed) : 'null'
}

function sqlInt(value) {
  const parsed = Number.parseInt(String(value ?? ''), 10)
  return Number.isFinite(parsed) ? String(parsed) : 'null'
}

function sqlTextArray(value) {
  const parts = String(value ?? '')
    .split(/[;|]/)
    .map(part => part.trim())
    .filter(Boolean)
  if (!parts.length) return "'{}'::text[]"
  return `array[${parts.map(sql).join(', ')}]::text[]`
}

function slugify(value) {
  return String(value ?? '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function scryfallUrl(row) {
  const setCode = String(row['Set code'] ?? '').toLowerCase()
  const collectorNumber = row['Collector number']
  if (!setCode || !collectorNumber) return ''
  return `https://scryfall.com/card/${setCode}/${collectorNumber}/${slugify(row.Name)}`
}

function sourceRowId(row) {
  return [
    row['Scryfall ID'],
    String(row['Set code'] ?? '').toLowerCase(),
    row['Collector number'],
    String(row.Foil ?? '').toLowerCase(),
  ].join('|')
}

function firstPresent(...values) {
  return values.map(value => String(value ?? '').trim()).find(Boolean) ?? ''
}

const cardCsv = readText(cardCsvPath)
const profileCsv = readText(profileCsvPath)
const cardRows = parseCsv(cardCsv).filter(row => row.Artist && row.Name)
const profileRows = parseCsv(profileCsv).filter(row => row.artist_name)
const profilesByArtist = new Map(profileRows.map(row => [row.artist_name, row]))
const artistsFromCatalog = [
  ...new Set([
    ...cardRows.map(row => row.Artist),
    ...profileRows.map(row => row.artist_name),
    ...atlantaAppearanceArtists,
  ]),
].sort((a, b) => a.localeCompare(b))
const atlantaArtistsFromCatalog = artistsFromCatalog.filter(artist => atlantaAppearanceArtists.has(artist))
const lines = []

lines.push('-- Generated by scripts/build_artist_card_catalog_seed_sql.mjs')
lines.push('-- Source CSVs remain ignored import evidence; canonical facts live in Supabase tables.')
lines.push('begin;')
lines.push(`
insert into public.artist_import_batches (source_name, source_path, source_sha256, source_kind, notes)
values
  ('Artist profiles normalized CSV', ${sql(path.relative(repoRoot, profileCsvPath).replaceAll('\\', '/'))}, ${sql(sha256(profileCsv))}, 'artist_profiles', 'Full local artist profile import for MagicCon Atlanta signing workflow'),
  ('Artist card taxonomy v2 with prices CSV', ${sql(path.relative(repoRoot, cardCsvPath).replaceAll('\\', '/'))}, ${sql(sha256(cardCsv))}, 'card_catalog', 'Full local card catalog import preserving rich v2 visual taxonomy and market prices')
on conflict (source_path, source_sha256) do update set imported_at = now(), notes = excluded.notes;
`)

for (const artist of artistsFromCatalog) {
  const profile = profilesByArtist.get(artist) ?? {}
  lines.push(`
insert into public.artists (
  canonical_name, display_name, scryfall_search_url, predominant_style, abstract_surreal_tendency,
  style_confidence, style_description, collection_card_count, unique_collection_printings,
  mtg_catalog_printings_found, earliest_mtg_credit_year, latest_mtg_credit_year,
  historical_style_signals, sample_mtg_cards, updated_at
) values (
  ${sql(artist)}, ${sql(artist)}, ${sql(`https://scryfall.com/search?as=grid&order=name&q=%28game%3Apaper%29+artist%3A${encodeURIComponent(artist.split(' ').at(-1) ?? artist)}+prefer%3Abest`)},
  ${sql(profile.predominant_style)}, ${sql(profile.abstract_surreal_tendency)}, ${sql(profile.style_confidence)},
  ${sql(profile.style_description)}, ${sqlInt(profile.collection_card_count)}, ${sqlInt(profile.unique_collection_printings)},
  ${sqlInt(profile.mtg_catalog_printings_found)}, ${sqlInt(profile.earliest_mtg_credit_year)}, ${sqlInt(profile.latest_mtg_credit_year)},
  ${sql(profile.historical_style_signals)}, ${sql(profile.sample_mtg_cards)}, now()
)
on conflict (canonical_name) do update set
  display_name = excluded.display_name,
  scryfall_search_url = excluded.scryfall_search_url,
  predominant_style = excluded.predominant_style,
  abstract_surreal_tendency = excluded.abstract_surreal_tendency,
  style_confidence = excluded.style_confidence,
  style_description = excluded.style_description,
  collection_card_count = excluded.collection_card_count,
  unique_collection_printings = excluded.unique_collection_printings,
  mtg_catalog_printings_found = excluded.mtg_catalog_printings_found,
  earliest_mtg_credit_year = excluded.earliest_mtg_credit_year,
  latest_mtg_credit_year = excluded.latest_mtg_credit_year,
  historical_style_signals = excluded.historical_style_signals,
  sample_mtg_cards = excluded.sample_mtg_cards,
  updated_at = now();
`)
}

for (const artist of atlantaArtistsFromCatalog) {
  const profile = profilesByArtist.get(artist) ?? {}
  const status = confirmedAtlantaArtists.has(artist) ? 'confirmed' : 'unconfirmed'
  lines.push(`
insert into public.artist_appearances (
  artist_id, event_key, attending_status, appearance_days, official_profile_url, source_note, priority_reason, updated_at
)
select id, 'magiccon_atlanta_2026', ${sql(status)}, 'All days', null,
  ${sql(status === 'confirmed' ? 'Official Atlanta guest page listed this artist during the POC pass.' : 'Kept visible as an unconfirmed signing candidate.')},
  ${sql(profile.priority_reason)}, now()
from public.artists
where canonical_name = ${sql(artist)}
on conflict (artist_id, event_key) do update set
  attending_status = excluded.attending_status,
  appearance_days = excluded.appearance_days,
  source_note = excluded.source_note,
  priority_reason = excluded.priority_reason,
  updated_at = now();
`)
}

for (const row of cardRows) {
  const rowId = sourceRowId(row)
  lines.push(`
with artist_row as (
  select id from public.artists where canonical_name = ${sql(row.Artist)}
), card_upsert as (
  insert into public.artist_cards (
    artist_id, scryfall_id, card_name, scryfall_url, card_image_url, art_crop_url, updated_at
  )
  select artist_row.id, ${sql(row['Scryfall ID'])}, ${sql(row.Name)}, ${sql(scryfallUrl(row))},
    ${sql(row['Card Image URL'])}, ${sql(row['Art Crop URL'])}, now()
  from artist_row
  on conflict (scryfall_id) do update set
    artist_id = excluded.artist_id,
    card_name = excluded.card_name,
    scryfall_url = excluded.scryfall_url,
    card_image_url = excluded.card_image_url,
    art_crop_url = excluded.art_crop_url,
    updated_at = now()
  returning id
), printing_upsert as (
  insert into public.artist_card_printings (
    card_id, source_row_id, set_code, set_name, collector_number, foil, rarity, quantity,
    market_price_usd, market_price_source_field, scryfall_usd, scryfall_usd_foil,
    scryfall_usd_etched, scryfall_eur, scryfall_eur_foil, scryfall_mtgo_tix,
    price_as_of, price_notes, printing_type, special_treatments, local_image_filename,
    local_image_found, updated_at
  )
  select card_upsert.id, ${sql(rowId)}, ${sql(row['Set code'])}, ${sql(row['Set name'])},
    ${sql(row['Collector number'])}, ${sql(row.Foil)}, ${sql(row.Rarity)}, coalesce(${sqlInt(row.Quantity)}, 1),
    ${sqlNumber(row['Market Price USD'])}, ${sql(row['Market Price Source Field'])},
    ${sqlNumber(row['Scryfall USD'])}, ${sqlNumber(row['Scryfall USD Foil'])}, ${sqlNumber(row['Scryfall USD Etched'])},
    ${sqlNumber(row['Scryfall EUR'])}, ${sqlNumber(row['Scryfall EUR Foil'])}, ${sqlNumber(row['Scryfall MTGO TIX'])},
    ${sql(row['Price As Of'])}, ${sql(row['Price Notes'])}, ${sql(row['Printing Type'])},
    ${sqlTextArray(row['Special Treatment'])}, ${sql(row['Image Filename'])}, ${row['Image Filename'] ? 'true' : 'false'}, now()
  from card_upsert
  on conflict (source_row_id) do update set
    card_id = excluded.card_id,
    set_code = excluded.set_code,
    set_name = excluded.set_name,
    collector_number = excluded.collector_number,
    foil = excluded.foil,
    rarity = excluded.rarity,
    quantity = excluded.quantity,
    market_price_usd = excluded.market_price_usd,
    market_price_source_field = excluded.market_price_source_field,
    scryfall_usd = excluded.scryfall_usd,
    scryfall_usd_foil = excluded.scryfall_usd_foil,
    scryfall_usd_etched = excluded.scryfall_usd_etched,
    scryfall_eur = excluded.scryfall_eur,
    scryfall_eur_foil = excluded.scryfall_eur_foil,
    scryfall_mtgo_tix = excluded.scryfall_mtgo_tix,
    price_as_of = excluded.price_as_of,
    price_notes = excluded.price_notes,
    printing_type = excluded.printing_type,
    special_treatments = excluded.special_treatments,
    local_image_filename = excluded.local_image_filename,
    local_image_found = excluded.local_image_found,
    updated_at = now()
  returning id
)
insert into public.artist_card_assessments (
  printing_id, card_art_category, surreal_abstract_focus, card_art_confidence,
  card_art_description, visual_art_category, visual_match_for_taste, visual_confidence,
  visual_assessment_notes, metadata_vs_visual, card_art_basis, card_art_tags, assessment_source, updated_at
)
select printing_upsert.id, ${sql(firstPresent(row['Art Taxonomy v2'], row['Card Art Category']))}, ${sql(firstPresent(row['Abstract/Surreal/Disproportion Fit'], row['Surreal/Abstract Focus']))},
  ${sql(firstPresent(row['Taxonomy v2 Confidence'], row['Card Art Confidence']))}, ${sql(firstPresent(row['Taxonomy v2 Description'], row['Card Art Description']))}, ${sql(row['Visual Art Category'])},
  ${sql(row['Visual Match for Your Taste'])}, ${sql(row['Visual Confidence'])}, ${sql(row['Visual Assessment Notes'])},
  ${sql(row['Metadata vs Visual'])}, ${sql(row['Card Art Basis'])}, ${sqlTextArray(row['Card Art Tags'])},
  'chatgpt_v2_artist_card_taxonomy', now()
from printing_upsert
on conflict (printing_id) do update set
  card_art_category = excluded.card_art_category,
  surreal_abstract_focus = excluded.surreal_abstract_focus,
  card_art_confidence = excluded.card_art_confidence,
  card_art_description = excluded.card_art_description,
  visual_art_category = excluded.visual_art_category,
  visual_match_for_taste = excluded.visual_match_for_taste,
  visual_confidence = excluded.visual_confidence,
  visual_assessment_notes = excluded.visual_assessment_notes,
  metadata_vs_visual = excluded.metadata_vs_visual,
  card_art_basis = excluded.card_art_basis,
  card_art_tags = excluded.card_art_tags,
  assessment_source = excluded.assessment_source,
  updated_at = now();
`)
}

lines.push('commit;')
fs.writeFileSync(outputPath, `${lines.join('\n')}\n`)

console.log(`Artist/card seed SQL written: ${path.relative(repoRoot, outputPath)}`)
console.log(`Artists in catalog: ${artistsFromCatalog.length}`)
console.log(`Atlanta appearances: ${atlantaArtistsFromCatalog.length}`)
console.log(`Card printings: ${cardRows.length}`)
